language: node_js
node_js:
  - "4.1"
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master
