language: node_js
node_js:
  - "5.10"
env:
  - CXX=g++4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASS
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master
